### ISSUE TITLE
List of members displays incorrectly

### ISSUE THREAD

**Issue by kailuowang** [alexanderjarvis/websocket-chat-dubsub#1]
First of all, great work! I am considering using dubsub and play-dubsub plugin in a project here at HuffingtonPost. 
You are probably aware of this, but the list of members on all instances are displaying members from whichever instance that published the latest message, rather than all members from all servers. I understand the point of this sample is to demonstrate the message publishing. It's just that this confused me a little bit.

**Comment by alexanderjarvis** [comment]
Hey, thanks! If you do get to use it, let me know and we can put it in the README of the main project. I have been using it in production myself in a project called [Meep](https://itunes.apple.com/gb/app/meep/id532580988?ls=1&mt=8).

Are you suggesting that the members of the chatroom don't appear until they have published a message? I guess that another type of message could be added to publish the presence of new members. I'm not sure without taking a look - the example itself is modified from the Play distribution and so it's not guaranteed to be a fully working chat room, it's just a demo.

**Comment by kailuowang** [comment]
Sure, will do. 
They don't appear until they published the message, and after they appear, members replaces the existing ones 
say userA and userB login throught localhost:9000 while userC and userD login through localhost:9001
after if userA post a message, member list on both instances will be userA and userB, if userD post a message, then member list on both instances will be userC and userD. I think this is probably what you expected when you do the simple implementation, it's just that when people first try this demo, they get a bit confused. That's all. Maybe a simple note in the readme will be a good enough "fix".
.
